package de.ait_tr.g_37_jp_shop.repository;

import de.ait_tr.g_37_jp_shop.domain.entity.Product;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

public interface ProductRepository extends JpaRepository<Product, Long> {

    // In this case body of method and SQL
    // request will be generated by Framework
//    Product findByTitle(String title);

    // In this case body of method will be generated by Framework
    // but SQL request
    @Query(value = "SELECT * FROM product WHERE title =  :title", nativeQuery = true)
    //Product findByTitle(@Param("title") String productTitle);
    Product findByTitle(String title);
}
